config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :authors

  get 'home/index'
  root to: 'readers/home#index'
  get '/blog/:id' => 'readers/posts#show', as: :blog_post

  scope module: 'authors' do
    get 'stats' => 'stats#index'
    resources :posts do
      resources :elements
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/models/element.rb
# frozen_string_literal: true

class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: %w[paragraph image video-embed] }

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/page_view.rb
# frozen_string_literal: true

class PageView < Impression
  scope :for_type, -> (type) do
    where(impressionable_type: type)
  end

  scope :for_date_range, -> (start_date, end_date) do
    where(created_at: start_date.beginning_of_day..end_date.end_of_day)
  end

  def self.count_by_date(start_date, end_date)
    results = for_date_range(start_date, end_date)
      .group('date(created_at)').count

    with_zeros(start_date, end_date, results)
  end

  def self.uniq_count_by_date(start_date, end_date)
    results = for_date_range(start_date, end_date)
      .select(:ip_address)
      .distinct.group('date(created_at)').count

    with_zeros(start_date, end_date, results)
  end

  def self.with_zeros(start_date, end_date, results_hash)
    date_range = (start_date.to_date..end_date.to_date).to_a.map do |date|
      date.strftime('%Y-%m-%d')
    end
    hash_with_zeros = {}
    date_range.each do |date|
      hash_with_zeros[date] = results_hash[date] || 0
    end
    hash_with_zeros
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged history finders]

  is_impressionable

  belongs_to :author
  has_many :elements, dependent: :destroy

  has_one_attached :header_image

  validates :title, :description, presence: true
  validates :description, length: { within: 50..250 }

  scope :published, -> do
    where(published: true)
  end

  scope :most_recently_published, -> do
    order(published_at: :desc)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/authors/elements_controller.rb
# frozen_string_literal: true

module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: %i[update destroy]

    # POST /elements
    def create
      @element = @post.elements.build(element_params)

      notice = if @element.save
                 nil
               else
                 @element.errors.full_messages.join('. ') << '.'
               end
      redirect_to edit_post_path(@post), notice: notice
    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      redirect_to edit_post_path(@element.post)
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_post_path(@element.post)
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.find(params[:post_id])
    end

    def set_element
      @element = @post.elements.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
  end
end

app/controllers/authors/posts_controller.rb
# frozen_string_literal: true

module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: %i[edit update destroy]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /posts
    def create
      @post = current_author.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        broadcast_errors @post, post_params
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        broadcast_errors @post, post_params
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :header_image)
    end
  end
end

app/controllers/authors/stats_controller.rb
# frozen_string_literal: true

module Authors
  class StatsController < AuthorsController
    def index
      @count_by_date = PageView.count_by_date(7.days.ago, Date.yesterday)
      @unique_count_by_date = PageView.uniq_count_by_date(7.days.ago, Date.yesterday)
    end
  end
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/readers/home_controller.rb
# frozen_string_literal: true

module Readers
  class HomeController < ReadersController
    def index
      @posts = Post.published.most_recently_published
    end
  end
end

app/controllers/readers/posts_controller.rb
# frozen_string_literal: true

module Readers
  class PostsController < ReadersController
    def show
      @post = Post.published.friendly.find(params[:id])
      impressionist(@post)
    end
  end
end

app/controllers/readers_controller.rb
# frozen_string_literal: true

class ReadersController < ApplicationController
  layout 'readers'
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/elements_helper.rb
# frozen_string_literal: true

module ElementsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/stats_helper.rb
# frozen_string_literal: true

module StatsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/posts/_form.html.erb
<%= form_with(model: post) do |form| %>

  <div class='form-group'>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
    <%= form.error_for :title, class: 'text-danger' %>
  </div>

  <div class='form-group'>
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
    <%= form.error_for :description, class: 'text-danger' %>
  </div>

  <div class='form-group'>
    <%= form.label :header_image %>
    <%= form.file_field :header_image %>
    <div class='mt-1'>
      <small>Current image:</small>
      <% if post.header_image.present? %>
        <%= image_tag(post.header_image, width: '100%') %>
      <% end %>
    </div>
  </div>

  <div class='actions'>
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class='row'>
  <div class='col-md-4'>
    <%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>
    <div class='card'>
      <div class='card-header'>
        <h6 class='card-title mb-0'>Editing Post</h6>
      </div>
      <div class='card-body'>
        <%= render 'form', post: @post %>
      </div>
      <div class='card-footer'>
        <% if @post.published? %>
          <a href='#'
             class='btn btn-secondary btn-block'
             data-reflex='click->PublisherReflex#unpublish'
             data-post-id='<%= @post.id %>'>
             Unpublish
          </a>
        <% else %>
          <a href='#'
             class='btn btn-dark btn-block'
             data-reflex='click->PublisherReflex#publish'
             data-post-id='<%= @post.id %>'>
            Publish
          </a>
        <% end %>
      </div>
    </div>
  </div>
  <div class='col-md-8'>
    <div class='mb-3'>
      <%= form_with(model: [@post, @element], html: { class: 'float-left mr-1' }) do |form| %>
        <%= form.hidden_field :element_type, value: 'paragraph' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class='fas fa-paragraph'></i>
        <% end %>
      <% end %>
      <%= form_with(model: [@post, @element]) do |form| %>
        <%= form.hidden_field :element_type, value: 'image' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class='fas fa-image'></i>
        <% end %>
      <% end %>
    </div>
    <div class='card mb-5'>
      <div class='card-header text-right'>
        <% if @post.published? %>
          <b>Publised</b> <%= time_ago_in_words(@post.published_at) %> ago
        <% else %>
          Unpublished
        <% end %>
      </div>
      <div class='card-body pt-5' data-controller='elements'>
        <% if @post.elements.none? { |element| element.persisted? } %>
          <div class='p-4 text-center'>
            <h2 class='text-secondary'>
              <i class='fas fa-lightbulb'></i>
            </h2>
            <p>Click the icons above to add elements to this posts.</p>
          </div>
        <% else %>
          <ul id='elements' data-action='drop->elements#sort'>
            <% @post.elements.each do |element| %>
              <% if element.persisted? %>
                <li data-id='<%= element.id %>' class='element-item'>
                  <% if element.paragraph? %>
                    <div class='mb-4 p-3 paragraph'>
                      <div class='paragraph-content'>
                        <% if element.content.present? %>
                          <%= element.content %>
                        <% else %>
                          <div class='p-0 text-center'>
                            <h6 class='text-secondary'>
                              <i class='far fa-keyboard fa-2x'></i>
                              <p>Click to add content.</p>
                            </h6>
                          </div>
                        <% end %>
                      </div>
                      <div class='paragraph-form d-none'>
                        <%= form_with(model: [@post, element]) do |form| %>
                          <%= form.rich_text_area :content %>
                          <div class='mt-3 d-flex justify-content-between'>
                            <div>
                              <%= form.submit 'Save', class: 'btn btn-primary' %>
                              <a href='#' class='cancel btn btn-secondary'>Cancel</a>
                            </div>
                            <%= link_to 'Delete', post_element_path(@post, element), method: :delete,
                                        class: 'btn btn-danger', data: { confirm: 'Are you sure?' }  %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  <% elsif element.image? %>
                    <div class='mb-4 p-3 image'>
                      <% if element.image.present? %>
                        <%= link_to post_element_path(@post, element), method: :delete,
                                    class: 'delete-btn btn btn-dark mt-2 float-right', data: { confirm: 'Are you sure?' } do %>
                          <i class='fas fa-times'></i>
                        <% end %>
                        <%= image_tag(element.image) %>
                      <% else %>
                        <%= form_with(model: [@post, element]) do |form| %>
                          <%= form.file_field :image %>
                          <div class='mt-3'>
                            <%= form.submit 'Save', class: 'btn btn-primary' %>
                            <a href='#' class='cancel btn btn-secondary'>Cancel</a>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/posts/index.html.erb
<h4 class='d-flex justify-content-between mb-4'>
  <span>Posts</span>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</h4>

<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
    <div class='card mb-3 post-card'>
      <div class='card-body'>
        <div class='row'>
          <div class='col-md-2'>
            <% if post.header_image.present? %>
              <div class='header-img' style='background-image: url(<%= url_for(post.header_image) %>)'></div>
            <% end %>
          </div>
          <div class='col-md-10'>
            <% if post.published? %>
              <span class='badge badge-primary mb-3'>Published</span>
            <% else %>
              <span class='badge badge-secondary mb-3'>Unpublihsed</span>
            <% end %>
            <h5 class='card-title mb-2 text-dark'><%= post.title %></h5>
            <p class='text-secondary mb-0'><%= post.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<div class='row'>
  <div class='col-md-4'>

    <%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>
    
    <div class='card'>
      <div class='card-header'>
        <h6 class='card-title mb-0'>New Post</h6>
      </div>
      <div class='card-body'>
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/authors/stats/index.html.erb
<h4 class='d-flex justify-content-between mb-4'>
  <span>Stats</span>
</h4>
<div class='row'>
  <div class='col-md-6'>
    <div class='card'>
      <div class='card-header'>
        7 Days Views
      </div>
      <div class='card-body'>
        <canvas id='page-views' width='400' height='400' data-labels='<%= @count_by_date.keys %>' data-data='<%= @count_by_date.values %>'></canvas>
      </div>
    </div>
  </div>
  <div class='col-md-6'>
    <div class='card'>
      <div class='card-header'>
        7 Days Unique Views
      </div>
      <div class='card-body'>
        <canvas id='unique-page-views' width='400' height='400' data-labels='<%= @unique_count_by_date.keys %>' data-data='<%= @unique_count_by_date.values %>'></canvas>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css'
          integrity='sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk'
          crossorigin='anonymous'>
    <script src='https://kit.fontawesome.com/9d3045fe19.js' crossorigin='anonymous'></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light authors'>
    <div class='container'>
      <p class='notice'><%= notice %></p>
      <p class='alert'><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/readers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css'
          integrity='sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk'
          crossorigin='anonymous'>
    <script src='https://kit.fontawesome.com/9d3045fe19.js' crossorigin='anonymous'></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light readers <%= controller_name %> <%= action_name %>'>
    <div class='container'>
      <p class='notice'><%= notice %></p>
      <p class='alert'><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/readers/home/index.html.erb
<div class='row'>
  <% @posts.each do |post| %>
    <div class='col-md-6 col-lg-4'>
      <div class='card post-card'>
        <div class='header-image' style='background-image: url(<%= url_for(post.header_image) %>)'></div>
        <div class='card-body d-flex flex-column'>
          <h5 class='card-title'><%= post.title %></h5>
          <p class='card-text'><%= truncate(post.description, length: 250) %></p>
          <%= link_to 'Read Post', blog_post_path(post), class: 'btn btn-primary mt-auto' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/readers/posts/show.html.erb
<div class='row'>
  <div class='col-lg-10 offset-lg-1'>
    <div class='card post-card mb-5'>
      <div class='header-image' style='background-image: url(<%= url_for(@post.header_image) %>)'></div>
      <div class='card-body'>
        <div class='p-5 pr-5 pt-4 pb-4'>
          <h1 class='card-title mb-5'><%= @post.title %></h1>
          <% @post.elements.each do |element| %>
            <% if element.image? %>
              <div class='image-element mb-5'>
                <%= image_tag(element.image) %>
              </div>
            <% else %>
              <div class='content-element mb-5'>
                <%= element.content %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>